env:
  global:
    - CC_TEST_REPORTER_ID=7b60d8ff462b5812be27ee306f7fef8547f9b5bfc141f29ee7b94a097ea65634
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  -  yarn test:pre-commit
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
